Genomes: "/gpfs/nobackup/stegle/users/casale/mksum/1000G/data/1000G_only4Eu.hdf5"
genodir: "/homes/hannah/data/LiMMBo/simulateData/genotypes/relatedEU_nopopstructure"
N: "10000"
paramGeno:
    seedGeno: "256"
    nAnc: 2
    nBlocks: 1000
    type: "only4Eu_noPop"
    maf: "0.02"
phenodir: "/homes/hannah/data/LiMMBo/simulateData/phenotypes"
S: "20"
